<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__dueDate</name>
   <tag></tag>
   <elementGuidId>6437b5ee-02d1-4374-90cf-93e0f104a77d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dueDate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dueDate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dfa30482-49d3-4abf-b22a-67ad82a6c680</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>23150447-c25f-449a-96d9-b302b1695a25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>5e08a540-19a0-4662-bb87-8df56f97f3a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-tns-c64-65 ui-inputtext ui-widget ui-state-default ui-corner-all ng-star-inserted</value>
      <webElementGuid>1fdb9a04-81c5-4ba6-a8a6-bcc84a8617ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>MM/DD/YYYY</value>
      <webElementGuid>e04c24fc-d82a-4a89-bace-3853791ff4c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>dueDate</value>
      <webElementGuid>f66b2381-20c0-4289-b074-0de6e5466a3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dueDate</value>
      <webElementGuid>757cb59d-c64c-47f2-a29b-23b24b7173fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dueDate&quot;)</value>
      <webElementGuid>2aae9438-0e21-43e3-90f1-30ac656bddab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dueDate']</value>
      <webElementGuid>2ed3f9fc-87fd-49ae-90ab-046764c817ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/div/div/app-case360/div[2]/div/div/div[2]/div/app-case360-activity/roots-dialog/div/div[2]/app-usertask/form/div/div[3]/div/roots-calendar/span/input</value>
      <webElementGuid>399e6589-fb24-4da5-a4ca-e97b00a82713</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/roots-calendar/span/input</value>
      <webElementGuid>8fd62670-bf66-42db-8ca3-b306959313e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'MM/DD/YYYY' and @id = 'dueDate']</value>
      <webElementGuid>f508bd42-8813-4757-af31-3756f928218d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
