<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Select</name>
   <tag></tag>
   <elementGuidId>b2e9f3b1-8a75-47db-93e4-4bb37a6c07e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//roots-dropdown[@inputid='businessProcess']//div//div//label[contains(text(),'Select')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>label.ng-tns-c50-692.ui-dropdown-label.ui-inputtext.ui-corner-all.ui-placeholder.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main']/div/div/app-case360/div[2]/div/div/div[2]/div/app-case360-activity/roots-dialog/div/div[2]/app-usertask/form/div/div/div/div/div/roots-dropdown/div/div[3]/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>44bf9ebe-9737-46d6-bbcf-62492bfd938e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-tns-c50-692 ui-dropdown-label ui-inputtext ui-corner-all ui-placeholder ng-star-inserted</value>
      <webElementGuid>56672e33-59d1-48ad-802f-66d0e5422e75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select</value>
      <webElementGuid>caadf50d-40af-4810-bb21-66d8e0cf7638</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//roots-dropdown[@inputid='businessProcess']//div//div//label[contains(text(),'Select')]</value>
      <webElementGuid>47e1df8b-b8f4-4880-95b4-052641d44a19</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/div/div/app-case360/div[2]/div/div/div[2]/div/app-case360-activity/roots-dialog/div/div[2]/app-usertask/form/div/div/div/div/div/roots-dropdown/div/div[3]/label</value>
      <webElementGuid>551009a1-182f-4e94-a6fb-901a71d01705</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::label[1]</value>
      <webElementGuid>b571379c-16b6-421a-a9aa-f334c937f62c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/preceding::label[1]</value>
      <webElementGuid>e4e3215f-f303-4b55-8496-eba83261a443</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/div/div/roots-dropdown/div/div[3]/label</value>
      <webElementGuid>4a93de5f-4efd-4f90-ab3c-2c5144db4010</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Select' or . = 'Select')]</value>
      <webElementGuid>c82bfa27-b3fe-46fb-96e6-9e016350b6cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
