<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Choose_ui-multiselect-trigger-icon ui-_8f5c02</name>
   <tag></tag>
   <elementGuidId>13c778b3-f2cc-454d-875a-9430b0a96cf0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//body/app-root/div/app-home/main[@id='main']/div/div/app-case360/div/div/div/div/div/app-case360-activity/roots-dialog/div[@role='dialog']/div/app-usertask/form/div/div/div/div/div/roots-multiselect[@placeholder='Select']/div/div/div/div/div[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.ui-multiselect-trigger-icon.ui-clickable.ng-tns-c54-68.fas.fa-angle-down</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main']/div/div/app-case360/div[2]/div/div/div[2]/div/app-case360-activity/roots-dialog/div/div[2]/app-usertask/form/div/div[6]/div/div/div/roots-multiselect/div/div[3]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>51e3f859-368d-413c-8e03-2978e5f2d2cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-multiselect-trigger-icon ui-clickable ng-tns-c54-68 fas fa-angle-down</value>
      <webElementGuid>68826b3c-d573-4274-a98e-1445258a4813</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//body/app-root/div/app-home/main[@id='main']/div/div/app-case360/div/div/div/div/div/app-case360-activity/roots-dialog/div[@role='dialog']/div/app-usertask/form/div/div/div/div/div/roots-multiselect[@placeholder='Select']/div/div/div/div/div[1]</value>
      <webElementGuid>3993508f-9bdc-4b58-b6e3-996770709b70</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/div/div/app-case360/div[2]/div/div/div[2]/div/app-case360-activity/roots-dialog/div/div[2]/app-usertask/form/div/div[6]/div/div/div/roots-multiselect/div/div[3]/span</value>
      <webElementGuid>f794458b-cd37-42b8-9de0-3dbf5a732921</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/roots-multiselect/div/div[3]/span</value>
      <webElementGuid>7f507ba9-1f51-4d16-9aa3-ffeaddeb5c22</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
