<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add Document</name>
   <tag></tag>
   <elementGuidId>57a88241-fccf-4023-b0ab-1b11c7c2e20b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#addDocument</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='addDocument']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cf9694ab-32cc-4d27-a7c7-435c6a5bf0a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addDocument</value>
      <webElementGuid>046bbcb0-e666-42fa-98ca-673c127ebf4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-2 mb-md-0 ml-sm-auto font-weight-bold text-primary mb-0 p-0 bg-white border-0 text-right</value>
      <webElementGuid>5f3bc23c-4327-45c8-b02b-318bcffc7951</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add Document</value>
      <webElementGuid>2d8aebec-a4a5-4f74-a63b-b56fce575c8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addDocument&quot;)</value>
      <webElementGuid>fedddc01-7bd6-4e2a-b7ed-bc24e720744d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='addDocument']</value>
      <webElementGuid>9c2ee074-ce04-413e-8315-11c2c431ed4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/div/div/app-case360/div[2]/div/div/div[2]/div/app-case360-document-selection/app-case360-documentupload/div[2]/div/div/div[3]/button</value>
      <webElementGuid>b9b7c11f-2814-4720-9884-e95c915e1cc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Right Pagination'])[1]/following::button[1]</value>
      <webElementGuid>4c6b0c04-212b-49ec-b347-922fb2137917</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='left Pagination'])[1]/following::button[2]</value>
      <webElementGuid>29448a3c-1ef7-4524-954a-bc18d72d44b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Doc Type'])[2]/preceding::button[1]</value>
      <webElementGuid>a9a16ebd-2aa2-403a-9000-af26d5a33429</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Document Title'])[1]/preceding::button[1]</value>
      <webElementGuid>69460891-061d-45ed-b72f-28c5b07c0fa8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add Document']/parent::*</value>
      <webElementGuid>85e6f597-9753-4dc4-a08c-afeea5257a8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[3]/button</value>
      <webElementGuid>5373390f-2c81-4756-a510-2a2feeec41b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'addDocument' and (text() = 'Add Document' or . = 'Add Document')]</value>
      <webElementGuid>3c67542e-0270-46c7-adba-0c08f0cc504f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
