<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_APPROVED_ml-2 fa-lg fas fa-chevron-circle-down</name>
   <tag></tag>
   <elementGuidId>f0f4b676-5825-4b53-b6de-2533aa97ee1c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.ml-2.fa-lg.fas.fa-chevron-circle-down</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='0']/td[5]/a/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>e06752b3-1da6-4888-8be2-ae2ea1b60fcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ml-2 fa-lg fas fa-chevron-circle-down</value>
      <webElementGuid>b2488f56-caad-4147-9459-78dd24aab1d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;0&quot;)/td[@class=&quot;expansion&quot;]/a[@class=&quot;font-weight-bold&quot;]/i[@class=&quot;ml-2 fa-lg fas fa-chevron-circle-down&quot;]</value>
      <webElementGuid>763d73be-e2ea-4b99-b7b1-50b03f3f15d5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='0']/td[5]/a/i</value>
      <webElementGuid>31a8a5e1-7f57-4de6-be64-2a4c61b65775</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/a/i</value>
      <webElementGuid>c25d437e-841f-42ce-8640-258589821a3e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
