<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Primary_ml-2 fa-lg fas fa-chevron-circle-down</name>
   <tag></tag>
   <elementGuidId>91263a00-0367-4999-b846-2c5c9d049be0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.ml-2.fa-lg.fas.fa-chevron-circle-down</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main']/div/div/app-case360/div[2]/div/div/div[2]/div/app-case360-document-selection/app-add-document-generation/div[2]/roots-table/div/div/table/tbody/tr/td[6]/a/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>8dc9c9e4-5d56-4a4f-a7bf-c331d83332d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>roots-tooltip</name>
      <type>Main</type>
      <value>Question</value>
      <webElementGuid>b3751478-f4fe-4f19-8379-0f2f83218547</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tooltipposition</name>
      <type>Main</type>
      <value>bottom</value>
      <webElementGuid>0c56ce1a-54f8-4ae7-bb08-e803a65f744b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ml-2 fa-lg fas fa-chevron-circle-down</value>
      <webElementGuid>380dedf0-8b25-476c-817f-a50c3fac39e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;bg-white min-height-600&quot;]/div[@class=&quot;bg-E3E3E3&quot;]/app-case360[@class=&quot;ng-star-inserted&quot;]/div[2]/div[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-9 col-xl-9 mb-3 mb-lg-0 pl-lg-0 pl-xl-0&quot;]/div[@class=&quot;clearfix h-100 bg-white&quot;]/app-case360-document-selection[@class=&quot;ng-star-inserted&quot;]/app-add-document-generation[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;app-tabview px-3&quot;]/roots-table[1]/div[@class=&quot;ui-table ui-widget&quot;]/div[@class=&quot;ui-table-wrapper ng-star-inserted&quot;]/table[1]/tbody[@class=&quot;ui-table-tbody&quot;]/tr[@class=&quot;ng-star-inserted&quot;]/td[@class=&quot;expansion&quot;]/a[@class=&quot;font-weight-bold&quot;]/i[@class=&quot;ml-2 fa-lg fas fa-chevron-circle-down&quot;]</value>
      <webElementGuid>3c6fd001-46b6-42da-8da6-536d464e8c25</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/div/div/app-case360/div[2]/div/div/div[2]/div/app-case360-document-selection/app-add-document-generation/div[2]/roots-table/div/div/table/tbody/tr/td[6]/a/i</value>
      <webElementGuid>e9636a43-e180-4c82-b2ee-18bb1d33632d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/a/i</value>
      <webElementGuid>6291734d-8821-40bc-96be-a59a75124b48</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
