<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>app-root_Processing request .Skip to main c_c3058f</name>
   <tag></tag>
   <elementGuidId>14cf1c64-92c9-4103-b583-1681ac35fe25</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//app-root</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>app-root</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>app-root</value>
      <webElementGuid>f75ec52b-0d59-4c80-8df9-094b7d43fa8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-version</name>
      <type>Main</type>
      <value>13.1.3</value>
      <webElementGuid>ef6021a4-7957-4b37-9918-68df4d39f6b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Processing request ...Skip to main contentMCDAVersion 9.0.0Menu Manage  Administration My WorkPress Enter to open the Dialog box and then use navigation keys to navigate29Notifications214Press Enter to open the Dialog box and then use navigation keys to navigate214balya I, Pradeep kumarPress Enter to open the Dialog box and then use navigation keys to navigate balya I, Pradeep kumar Name  Case #  LEA #  Court File #  Case Title  Case Keyword  Name  Name (Soundex)  Person SID #  Person ID  Physical File #  Note  All label for searchText No Results FoundInclude Inactive Case TypesInclude Inactive ValuesInclude Temp Cases Case Type Choose Item SelectSelect Operator SelectSelect Value(s)  Hidden TextAddNo Filters AppliedCancelResetSearchSaved SearchesQuick Searchlabel for searchTextAdvance FilterHomeCaseCase Intake  - Adult CriminalPrintSaveCancel×1Incidents2Case Information3Participants4Charges5Assigned Staff6ReviewLEA # *Offense From Date *ui-btnOffense To Dateui-btnLEA *SelectAdult and Family Services Adult and Family ServicesFactsLocation DescriptionNotesAttachments Add Attachments  Doc Type   Document Title   Uploaded   Status  Doc Type:  Police Report  Document Title:  Document Title  Uploaded:  12/21/2022 01:19 PM Status:  Pending  Expansion LinkAddress Details Add Address  No Records found Add Address   Hidden TextNo AddressAddress Line 1*Address Line 2Address Line 3Zip*City*SelectSelectCounty*SelectBenton BentonState*SelectOR ORCountry*SelectUnited States United StatesCommentsSaveCancelSaveCancel Company Overview  Leadership  Policies  Services  Industries  Partners COPYRIGHT 2020 HTC Global Services.</value>
      <webElementGuid>8ddbb7e8-fd14-451e-8b14-299027775687</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]</value>
      <webElementGuid>aca29a31-0f26-47e2-b52f-a1973d15b49b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-root</value>
      <webElementGuid>ad74ded4-ea1d-415c-bb07-39d975f94ac5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//app-root[(text() = 'Processing request ...Skip to main contentMCDAVersion 9.0.0Menu Manage  Administration My WorkPress Enter to open the Dialog box and then use navigation keys to navigate29Notifications214Press Enter to open the Dialog box and then use navigation keys to navigate214balya I, Pradeep kumarPress Enter to open the Dialog box and then use navigation keys to navigate balya I, Pradeep kumar Name  Case #  LEA #  Court File #  Case Title  Case Keyword  Name  Name (Soundex)  Person SID #  Person ID  Physical File #  Note  All label for searchText No Results FoundInclude Inactive Case TypesInclude Inactive ValuesInclude Temp Cases Case Type Choose Item SelectSelect Operator SelectSelect Value(s)  Hidden TextAddNo Filters AppliedCancelResetSearchSaved SearchesQuick Searchlabel for searchTextAdvance FilterHomeCaseCase Intake  - Adult CriminalPrintSaveCancel×1Incidents2Case Information3Participants4Charges5Assigned Staff6ReviewLEA # *Offense From Date *ui-btnOffense To Dateui-btnLEA *SelectAdult and Family Services Adult and Family ServicesFactsLocation DescriptionNotesAttachments Add Attachments  Doc Type   Document Title   Uploaded   Status  Doc Type:  Police Report  Document Title:  Document Title  Uploaded:  12/21/2022 01:19 PM Status:  Pending  Expansion LinkAddress Details Add Address  No Records found Add Address   Hidden TextNo AddressAddress Line 1*Address Line 2Address Line 3Zip*City*SelectSelectCounty*SelectBenton BentonState*SelectOR ORCountry*SelectUnited States United StatesCommentsSaveCancelSaveCancel Company Overview  Leadership  Policies  Services  Industries  Partners COPYRIGHT 2020 HTC Global Services.' or . = 'Processing request ...Skip to main contentMCDAVersion 9.0.0Menu Manage  Administration My WorkPress Enter to open the Dialog box and then use navigation keys to navigate29Notifications214Press Enter to open the Dialog box and then use navigation keys to navigate214balya I, Pradeep kumarPress Enter to open the Dialog box and then use navigation keys to navigate balya I, Pradeep kumar Name  Case #  LEA #  Court File #  Case Title  Case Keyword  Name  Name (Soundex)  Person SID #  Person ID  Physical File #  Note  All label for searchText No Results FoundInclude Inactive Case TypesInclude Inactive ValuesInclude Temp Cases Case Type Choose Item SelectSelect Operator SelectSelect Value(s)  Hidden TextAddNo Filters AppliedCancelResetSearchSaved SearchesQuick Searchlabel for searchTextAdvance FilterHomeCaseCase Intake  - Adult CriminalPrintSaveCancel×1Incidents2Case Information3Participants4Charges5Assigned Staff6ReviewLEA # *Offense From Date *ui-btnOffense To Dateui-btnLEA *SelectAdult and Family Services Adult and Family ServicesFactsLocation DescriptionNotesAttachments Add Attachments  Doc Type   Document Title   Uploaded   Status  Doc Type:  Police Report  Document Title:  Document Title  Uploaded:  12/21/2022 01:19 PM Status:  Pending  Expansion LinkAddress Details Add Address  No Records found Add Address   Hidden TextNo AddressAddress Line 1*Address Line 2Address Line 3Zip*City*SelectSelectCounty*SelectBenton BentonState*SelectOR ORCountry*SelectUnited States United StatesCommentsSaveCancelSaveCancel Company Overview  Leadership  Policies  Services  Industries  Partners COPYRIGHT 2020 HTC Global Services.')]</value>
      <webElementGuid>9321e5ec-aba8-420a-a4e4-aae1d8d3c566</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
