<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Assigned To drop down</name>
   <tag></tag>
   <elementGuidId>1c9812b7-818b-465f-811e-cbb7ad99c452</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//roots-dropdown[@inputid='AssignedStaff']//div//div//label[contains(text(),'Select')]
</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>label.ng-tns-c48-22.ui-dropdown-label.ui-inputtext.ui-corner-all.ui-placeholder.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@class='ng-tns-c50-210 ui-dropdown-label ui-inputtext ui-corner-all ui-placeholder ng-star-inserted']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>4f02a309-29c1-432b-b9a7-66c9918f83e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-tns-c48-22 ui-dropdown-label ui-inputtext ui-corner-all ui-placeholder ng-star-inserted</value>
      <webElementGuid>0c7968d6-9831-4c53-833d-077e62557554</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select</value>
      <webElementGuid>675eced4-6f10-484c-94b7-13e51a248983</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//roots-dropdown[@inputid='AssignedStaff']//div//div//label[contains(text(),'Select')]
</value>
      <webElementGuid>75c8cc81-0be7-4ad0-80d7-ff6c79173eb1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='test']/div/div/form/div/div/div[2]/div/div[4]/div/roots-dropdown/div/div[4]/span</value>
      <webElementGuid>8f2d7ec0-edb4-44ef-a6a9-df2cd504dbf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::label[1]</value>
      <webElementGuid>23dc109f-7025-442e-9b18-7f359da97e26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/preceding::label[1]</value>
      <webElementGuid>aeb3f47b-d905-48ff-9a2c-3b80ece8de0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/roots-dropdown/div/div[3]/label</value>
      <webElementGuid>c6ec39d2-75b5-4077-b209-62b181df8a67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Select' or . = 'Select')]</value>
      <webElementGuid>2792a131-677c-4519-bbf7-aee56ff6b9bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//main[@id='main']/div/div/app-case-intake/div[2]/div/div/div/div/div/div[2]/div/div/div/div/app-assigned-staff/roots-dialog/div/div[2]/form/div/div/div[3]/div/roots-dropdown/div/div[4]/span</value>
      <webElementGuid>97b43750-d2f6-493b-a6da-26e64e10ed9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//label[@class='ng-tns-c50-210 ui-dropdown-label ui-inputtext ui-corner-all ui-placeholder ng-star-inserted']</value>
      <webElementGuid>c27da684-7e9a-43bf-b6f7-3aabefed5ff7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
