<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Count     Added for  On 12292022 0100 P_1911ad</name>
   <tag></tag>
   <elementGuidId>48fd1b50-c234-4ef7-81cf-977601a914f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ui-panel-19-label']/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.row.ng-tns-c76-84 > div.col-md-6</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c18273cc-5b1a-4318-b630-3dfff9fa6058</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-md-6</value>
      <webElementGuid>48e7a836-24e7-41e2-97a8-c8807cd6fd41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Count     Added for  On 12/29/2022 01:00 PM balya I, Pradeep kumar Case Created  On 12/29/2022 01:00 PM balya I, Pradeep kumar   Added On 12/29/2022 12:58 PM balya I, Pradeep kumar</value>
      <webElementGuid>f3156f22-8680-45bf-b84d-b5f1c5d04b58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-panel-19-label&quot;)/div[@class=&quot;ui-panel-content ui-widget-content ng-tns-c76-84&quot;]/div[@class=&quot;row ng-tns-c76-84&quot;]/div[@class=&quot;col-md-6&quot;]</value>
      <webElementGuid>553890cd-e584-4c9b-82d5-b4c31c226139</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ui-panel-19-label']/div/div/div</value>
      <webElementGuid>2a4b3569-3e3d-4864-b6fa-f019180f85e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recent Activity'])[1]/following::div[4]</value>
      <webElementGuid>f0be9e8a-5826-4e87-94c1-f7fe850f1e96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Expansion Link'])[1]/following::div[34]</value>
      <webElementGuid>eda8d61c-3811-4cbd-ae84-a47fe20ea979</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/roots-panel/div/div[2]/div/div/div</value>
      <webElementGuid>351e3da3-bf30-4ce4-a88a-4d4e53edfd4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' Count     Added for  On 12/29/2022 01:00 PM balya I, Pradeep kumar Case Created  On 12/29/2022 01:00 PM balya I, Pradeep kumar   Added On 12/29/2022 12:58 PM balya I, Pradeep kumar' or . = ' Count     Added for  On 12/29/2022 01:00 PM balya I, Pradeep kumar Case Created  On 12/29/2022 01:00 PM balya I, Pradeep kumar   Added On 12/29/2022 12:58 PM balya I, Pradeep kumar')]</value>
      <webElementGuid>f38d83c9-6d68-4480-be47-3512d67db686</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
