<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Case Detail TypeSelectSelectCase Detail_23a932</name>
   <tag></tag>
   <elementGuidId>58102027-62aa-450b-a06b-16daaec00632</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main']/div/div/app-case-intake/div[2]/div/div/div/div/div/div[2]/div/div/div/div[2]/app-case-detail/form/roots-dialog/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ui-dialog-content.ui-widget-content.ng-tns-c50-42</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5fe9d50f-e064-4ef4-bebd-db9a9900e811</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-dialog-content ui-widget-content ng-tns-c50-42</value>
      <webElementGuid>e183d539-b6f8-452c-8824-5dc9f8662d1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Case Detail Type*SelectSelectCase DetailSaveCancel</value>
      <webElementGuid>28ffb2bb-95eb-469e-a463-65a939d0f5ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;bg-white min-height-600&quot;]/div[1]/app-case-intake[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[1]/div[@class=&quot;d-block d-md-flex bg-white mb-3&quot;]/div[@class=&quot;flex-fill h-100 bg-white pb-3 caseIntakePage-cont&quot;]/div[@class=&quot;bg-white mb-3&quot;]/div[@class=&quot;clearfix&quot;]/div[@class=&quot;d-block d-md-flex&quot;]/div[@class=&quot;row flex-fill h-100 bg-white position-relative caseIntakePage-cont&quot;]/div[@class=&quot;col-md-12 ng-star-inserted&quot;]/div[@class=&quot;mb-2 ng-star-inserted&quot;]/app-case-detail[1]/form[@class=&quot;ng-pristine ng-invalid ng-touched&quot;]/roots-dialog[@class=&quot;ng-tns-c50-42 ng-star-inserted&quot;]/div[@class=&quot;ng-trigger ng-trigger-animation ng-tns-c50-42 col-md-10 col-lg-8 col-xl-6 px-0 ui-dialog ui-widget ui-widget-content ui-corner-all ui-shadow ui-dialog-resizable ng-star-inserted ng-animating&quot;]/div[@class=&quot;ui-dialog-content ui-widget-content ng-tns-c50-42&quot;]</value>
      <webElementGuid>c753efb8-d4e3-4560-b4b7-a8d4c31e84d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/div/div/app-case-intake/div[2]/div/div/div/div/div/div[2]/div/div/div/div[2]/app-case-detail/form/roots-dialog/div/div[2]</value>
      <webElementGuid>f320babb-080a-447e-b8d5-d6c4a3dbfeb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Case Detail'])[2]/following::div[1]</value>
      <webElementGuid>4a61e9c5-6b76-4e3f-a49d-d6c76d448ee6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[1]/following::div[3]</value>
      <webElementGuid>b1e46206-6294-48fe-9835-bf2518896116</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//roots-dialog/div/div[2]</value>
      <webElementGuid>31be915c-d7f1-4800-b21d-8287c8d497f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Case Detail Type*SelectSelectCase DetailSaveCancel' or . = 'Case Detail Type*SelectSelectCase DetailSaveCancel')]</value>
      <webElementGuid>f7b008ca-528d-4e48-a00f-f2c928c15099</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
