<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Enter__LEA</name>
   <tag></tag>
   <elementGuidId>acf09f1f-3f35-4b3b-966a-502d53e6c77c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#CitationNum</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='CitationNum']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>74ab282f-d18d-45c6-9001-deddd190126b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4648e1d5-ff8d-430e-8dd9-c5f2d65f132b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>CitationNum</value>
      <webElementGuid>97ca681d-b827-4bfd-84cb-6e7718445253</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>CitationNum1</value>
      <webElementGuid>719603e0-db82-4177-b991-897d8e2d849d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>0b2b9543-e5ca-442a-864c-2faf149e8712</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CitationNum</value>
      <webElementGuid>d38e7af9-49b7-4cd0-8d8c-93d82cde07a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-invalid ng-touched</value>
      <webElementGuid>f702b14e-cba1-4270-9e2e-ad467faa8407</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CitationNum&quot;)</value>
      <webElementGuid>cdd5a86a-bb5b-4640-acec-5e1f67941c00</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='CitationNum']</value>
      <webElementGuid>f4629c91-af9d-4769-8b5b-e0af35657223</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='test']/div/div/form/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>8ec7309a-4b00-4c56-95bb-5ffa167c498b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>573685de-f57c-4f65-ba93-4553bc6a85f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'CitationNum']</value>
      <webElementGuid>230b2797-f082-473a-9d52-34421f38a910</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
