<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Home</name>
   <tag></tag>
   <elementGuidId>7a2538c0-5e6d-4744-98ba-5a6ff20a5a93</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//*[@class='ui-menuitem-text'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.ui-menuitem-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d1970362-441e-4305-837e-692da817e7cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-menuitem-text</value>
      <webElementGuid>c174dc93-0aa3-46fd-bb5c-3aecbcfeb964</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Home</value>
      <webElementGuid>0e8fff88-f222-4126-a032-82daa3b57142</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;bg-white min-height-600&quot;]/div[@class=&quot;bg-E3E3E3&quot;]/app-dashboard[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;pageHeader py-3&quot;]/div[@class=&quot;row align-items-center h-100&quot;]/div[@class=&quot;col-md-6 mb-2 mb-md-0&quot;]/div[@class=&quot;clearfix breadCrumb&quot;]/app-breadcrumb[1]/roots-breadcrumb[@class=&quot;float-left&quot;]/div[@class=&quot;ui-breadcrumb ui-widget ui-widget-header ui-helper-clearfix ui-corner-all&quot;]/ul[1]/li[@class=&quot;ng-star-inserted&quot;]/a[@class=&quot;ui-menuitem-link ng-star-inserted&quot;]/span[@class=&quot;ui-menuitem-text&quot;]</value>
      <webElementGuid>fa7f2957-81d0-4ad4-bd03-9884040998a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/div/div/app-dashboard/div/div/div/div/div/div/app-breadcrumb/roots-breadcrumb/div/ul/li/a/span</value>
      <webElementGuid>fe5a0999-4969-4be4-8380-b3f6feeaf87e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Advance Filter'])[1]/following::span[1]</value>
      <webElementGuid>31465418-881d-4f41-83a8-37e6b566128c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='label for searchText'])[2]/following::span[3]</value>
      <webElementGuid>074a611e-19b7-4042-8e6f-3f3c205b9ceb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DASHBOARD – Application Home'])[1]/preceding::span[2]</value>
      <webElementGuid>2d368243-7e34-4937-8c88-a4d0db56095a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Program Metrics'])[1]/preceding::span[2]</value>
      <webElementGuid>a30c0cab-e165-49c5-bd7f-185bb70ce7be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Home']/parent::*</value>
      <webElementGuid>fc8157c1-9dfb-4f00-94e2-61a6ac569bb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//roots-breadcrumb/div/ul/li/a/span</value>
      <webElementGuid>b6b962e7-2824-4bf9-9d1a-eacc63b8579f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Home' or . = 'Home')]</value>
      <webElementGuid>928a20ee-8460-446d-a042-0ff87281d9c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
