<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Primary Phone_ml-2 fa-lg fas fa-chevron-c_5e1b60</name>
   <tag></tag>
   <elementGuidId>cb27efcb-2293-40b4-be0d-ad6348e80f1e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ui-panel-26-label']/div/div/div[2]/roots-table/div/div/table/tbody/tr/td[6]/a/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.ml-2.fa-lg.fas.fa-chevron-circle-down</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>8c66cb8b-0e37-4542-bea9-6b7f7f734105</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ml-2 fa-lg fas fa-chevron-circle-down</value>
      <webElementGuid>ad8587a5-2663-4758-98e1-2d035d6147b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-panel-26&quot;)/div[@id=&quot;ui-panel-26-label&quot;]/div[@class=&quot;ui-panel-content ui-widget-content ng-tns-c76-95&quot;]/div[@class=&quot;clearfix ng-tns-c76-95&quot;]/div[@class=&quot;app-tabview bg-white&quot;]/roots-table[1]/div[@class=&quot;ui-table ui-widget&quot;]/div[@class=&quot;ui-table-wrapper ng-star-inserted&quot;]/table[1]/tbody[@class=&quot;ui-table-tbody&quot;]/tr[@class=&quot;ng-star-inserted&quot;]/td[@class=&quot;expansion&quot;]/a[@class=&quot;font-weight-bold&quot;]/i[@class=&quot;ml-2 fa-lg fas fa-chevron-circle-down&quot;]</value>
      <webElementGuid>c0b084c6-7516-4036-9494-892bc22bd93f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ui-panel-26-label']/div/div/div[2]/roots-table/div/div/table/tbody/tr/td[6]/a/i</value>
      <webElementGuid>01b64935-04df-47d3-b840-5260e1607b71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/a/i</value>
      <webElementGuid>42d8bebe-5284-47d4-9626-92295ada6797</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
