<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Incident_Attachment_Save</name>
   <tag></tag>
   <elementGuidId>36fe1515-b332-4bca-8117-710de1362fa7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//button[contains(text(),'Save')])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//button[contains(text(),'Save')])[2]</value>
      <webElementGuid>d79e1eaf-3a48-447e-958a-1db77f7bceea</webElementGuid>
   </webElementProperties>
</WebElementEntity>
