<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Offense To Date_EndDate</name>
   <tag></tag>
   <elementGuidId>1f3497a8-5850-4492-9f82-dc77a194fe82</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='EndDate']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#EndDate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f7417aac-8418-42f9-a5c8-6f75927d2da0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>07efa0a2-f87d-4f90-beb1-2cb7c59e72f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>1b289986-ac36-430a-b170-a20d880ab0a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-tns-c62-44 ui-inputtext ui-widget ui-state-default ui-corner-all ng-star-inserted</value>
      <webElementGuid>fa422627-4678-4c0e-a25a-606899a40273</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>MM/DD/YYYY</value>
      <webElementGuid>26c9328f-2cb6-4a5d-af2a-cb46410feb11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>EndDate</value>
      <webElementGuid>b9088ef2-8473-438e-9c0d-eba77b3a476c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>EndDate</value>
      <webElementGuid>06c54559-6573-4f47-82f2-79701ab0f66a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;EndDate&quot;)</value>
      <webElementGuid>6840a4e2-5eb4-428c-b729-3cea23103ce5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='EndDate']</value>
      <webElementGuid>762b9ca5-297d-4541-96d0-bb34a0be1d19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='test']/div/div/form/div/div/div[2]/div/div[3]/div/roots-calendar/span/input</value>
      <webElementGuid>fbfbf9eb-44cd-4ff2-b020-84a3a778ae26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/roots-calendar/span/input</value>
      <webElementGuid>bd9f9bb1-8210-47cd-86b9-fdfbc22f9005</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'MM/DD/YYYY' and @id = 'EndDate']</value>
      <webElementGuid>95caf108-6c7e-49bf-b043-7c126019861c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
