<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__ZipCodeId</name>
   <tag></tag>
   <elementGuidId>a4008cb5-7eb0-4cfd-95ba-36384c190dc7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ZipCodeId']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ZipCodeId</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bf0a9fcf-4188-43a1-abe3-de1594586934</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ZipCodeId</value>
      <webElementGuid>77b69c08-20a3-43f5-9029-3a7577bc9d90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>17045c6f-e860-48f4-b5df-59548ac3af8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>ZipCodeId</value>
      <webElementGuid>1bba8fe2-d416-4372-b229-28ec08d7ade6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return (event.charCode >= 48 &amp;&amp; event.charCode &lt;= 57)</value>
      <webElementGuid>04c1d7bd-ebca-48ff-a30d-ddc07827f6f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>1a2d65e1-4d97-4867-8d26-b726124992ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-valid ng-star-inserted</value>
      <webElementGuid>de7c0455-8450-4153-b265-3b0cc023ae5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ZipCodeId&quot;)</value>
      <webElementGuid>19b75a48-7952-4e0a-a7b5-00148a72ab26</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ZipCodeId']</value>
      <webElementGuid>6c0c67f4-5ed6-4c70-ae86-93b1f03df1ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='test']/div/div/form/div/div/div[2]/div[4]/app-participant-editparticipant-address/roots-dialog/div/div[2]/form/div/div[5]/div/input</value>
      <webElementGuid>626c86a6-0cbc-4d15-aad7-87b5a721e027</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/input</value>
      <webElementGuid>21b3cd33-6f17-47b7-b1d1-d4ad08bbc14d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ZipCodeId' and @type = 'text']</value>
      <webElementGuid>a054468a-dfb9-44a8-be6a-1b4ed5fad20d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
