<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Staff Type Dropdown</name>
   <tag></tag>
   <elementGuidId>c699085c-3d0c-423d-8dac-8cda6716fa8d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//roots-dropdown[@inputid='AssignedTypeStaff']//div//div//label[contains(text(),'Select')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.ui-dropdown-trigger-icon.ui-clickable.ng-tns-c48-206.fas.fa-angle-down</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//roots-dropdown[@inputid='AssignedTypeStaff']//div//div//label[contains(text(),'Select')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d3800aac-37e5-4963-b915-b794f9d92f43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-dropdown-trigger-icon ui-clickable ng-tns-c48-206 fas fa-angle-down</value>
      <webElementGuid>76440020-83e0-4af7-8977-00d2517d48da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//roots-dropdown[@inputid='AssignedTypeStaff']//div//div//label[contains(text(),'Select')]</value>
      <webElementGuid>a04d3a0b-c8f0-4722-a035-b22a278ace01</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/div/div/app-case-intake/div[2]/div/div/div/div/div/div[2]/div/div/div/div/app-assigned-staff/roots-dialog/div/div[2]/form/div/div/div/div/roots-dropdown/div/div[4]/span</value>
      <webElementGuid>193e01eb-f24c-4ac0-a539-d8a164677c46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/div/roots-dropdown/div/div[4]/span</value>
      <webElementGuid>58814997-d6ba-4081-882b-36d911be643d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//*[@id=&quot;main&quot;]/div/div/app-case-intake/div[2]/div/div/div/div/div/div[2]/div/div/div/div[1]/app-assigned-staff/roots-dialog/div/div[2]/form/div/div/div[1]/div/roots-dropdown/div/div[4]</value>
      <webElementGuid>859835fc-04d8-4036-965c-5f90407091c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
