<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>app-root_Processing request .Skip to main c_e5b108</name>
   <tag></tag>
   <elementGuidId>4587980b-32de-49dd-a476-ea2e3f6b2c87</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>app-root</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//app-root</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>app-root</value>
      <webElementGuid>138a23bf-88cc-4ad0-a211-de6bd323ee78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-version</name>
      <type>Main</type>
      <value>13.1.3</value>
      <webElementGuid>b1c04df5-da0a-4c3c-887c-be23219ded1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Processing request ...Skip to main contentMCDAVersion 9.0.0Menu Manage  Administration My WorkPress Enter to open the Dialog box and then use navigation keys to navigate30Notifications216Press Enter to open the Dialog box and then use navigation keys to navigate216balya I, Pradeep kumarPress Enter to open the Dialog box and then use navigation keys to navigate balya I, Pradeep kumar Name  Case #  LEA #  Court File #  Case Title  Case Keyword  Name  Name (Soundex)  Person SID #  Person ID  Physical File #  Note  All label for searchText No Results FoundInclude Inactive Case TypesInclude Inactive ValuesInclude Temp Cases Case Type Choose Item SelectSelect Operator SelectSelect Value(s)  Hidden TextAddNo Filters AppliedCancelResetSearchSaved SearchesQuick Searchlabel for searchTextAdvance FilterHome3002695Case # 3002695 balya, pradeep kumar, MR.I want to ...Add File LocationAdd New ParticipantAdd Participant InteractionAdd TaskAssign CaseCopy CaseExpunge/UnexpungeSchedule Grand JuryCase Snapshot Add NoteStatus:Pending Review (12/29/2022)Assigned To:DV DDAs  Next Up: N/A Case OverviewParticipants1Case Charges0Costs2DetailDocuments2Events2Evidence0File Location0Incidents1Notes2Tasks1Witness Management0Case ParticipantsView ParticipantsType or press Enter to show the case participantsFile Location Showing 1 - 0of 0 10 10left PaginationRight PaginationAdd File Location File Location  Transfer Date &amp; Time  Participants  Archive Control Number/Box  No Records found  Add File Location  Case # 3002695File Location*SelectDV Unit DV UnitTransfer Date*ui-btnParticipantsDefendant-1-balya MR., pradeep kumarArchive Control #Box #NotesSaveCancel Company Overview  Leadership  Policies  Services  Industries  Partners COPYRIGHT 2020 HTC Global Services.</value>
      <webElementGuid>55470e08-43bd-4675-b87b-09558a64354f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]</value>
      <webElementGuid>d6f1b295-e97a-4919-94c4-3ae02629bff9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-root</value>
      <webElementGuid>11e098fb-ceb9-4e7a-861d-5ec843ceed16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//app-root[(text() = 'Processing request ...Skip to main contentMCDAVersion 9.0.0Menu Manage  Administration My WorkPress Enter to open the Dialog box and then use navigation keys to navigate30Notifications216Press Enter to open the Dialog box and then use navigation keys to navigate216balya I, Pradeep kumarPress Enter to open the Dialog box and then use navigation keys to navigate balya I, Pradeep kumar Name  Case #  LEA #  Court File #  Case Title  Case Keyword  Name  Name (Soundex)  Person SID #  Person ID  Physical File #  Note  All label for searchText No Results FoundInclude Inactive Case TypesInclude Inactive ValuesInclude Temp Cases Case Type Choose Item SelectSelect Operator SelectSelect Value(s)  Hidden TextAddNo Filters AppliedCancelResetSearchSaved SearchesQuick Searchlabel for searchTextAdvance FilterHome3002695Case # 3002695 balya, pradeep kumar, MR.I want to ...Add File LocationAdd New ParticipantAdd Participant InteractionAdd TaskAssign CaseCopy CaseExpunge/UnexpungeSchedule Grand JuryCase Snapshot Add NoteStatus:Pending Review (12/29/2022)Assigned To:DV DDAs  Next Up: N/A Case OverviewParticipants1Case Charges0Costs2DetailDocuments2Events2Evidence0File Location0Incidents1Notes2Tasks1Witness Management0Case ParticipantsView ParticipantsType or press Enter to show the case participantsFile Location Showing 1 - 0of 0 10 10left PaginationRight PaginationAdd File Location File Location  Transfer Date &amp; Time  Participants  Archive Control Number/Box  No Records found  Add File Location  Case # 3002695File Location*SelectDV Unit DV UnitTransfer Date*ui-btnParticipantsDefendant-1-balya MR., pradeep kumarArchive Control #Box #NotesSaveCancel Company Overview  Leadership  Policies  Services  Industries  Partners COPYRIGHT 2020 HTC Global Services.' or . = 'Processing request ...Skip to main contentMCDAVersion 9.0.0Menu Manage  Administration My WorkPress Enter to open the Dialog box and then use navigation keys to navigate30Notifications216Press Enter to open the Dialog box and then use navigation keys to navigate216balya I, Pradeep kumarPress Enter to open the Dialog box and then use navigation keys to navigate balya I, Pradeep kumar Name  Case #  LEA #  Court File #  Case Title  Case Keyword  Name  Name (Soundex)  Person SID #  Person ID  Physical File #  Note  All label for searchText No Results FoundInclude Inactive Case TypesInclude Inactive ValuesInclude Temp Cases Case Type Choose Item SelectSelect Operator SelectSelect Value(s)  Hidden TextAddNo Filters AppliedCancelResetSearchSaved SearchesQuick Searchlabel for searchTextAdvance FilterHome3002695Case # 3002695 balya, pradeep kumar, MR.I want to ...Add File LocationAdd New ParticipantAdd Participant InteractionAdd TaskAssign CaseCopy CaseExpunge/UnexpungeSchedule Grand JuryCase Snapshot Add NoteStatus:Pending Review (12/29/2022)Assigned To:DV DDAs  Next Up: N/A Case OverviewParticipants1Case Charges0Costs2DetailDocuments2Events2Evidence0File Location0Incidents1Notes2Tasks1Witness Management0Case ParticipantsView ParticipantsType or press Enter to show the case participantsFile Location Showing 1 - 0of 0 10 10left PaginationRight PaginationAdd File Location File Location  Transfer Date &amp; Time  Participants  Archive Control Number/Box  No Records found  Add File Location  Case # 3002695File Location*SelectDV Unit DV UnitTransfer Date*ui-btnParticipantsDefendant-1-balya MR., pradeep kumarArchive Control #Box #NotesSaveCancel Company Overview  Leadership  Policies  Services  Industries  Partners COPYRIGHT 2020 HTC Global Services.')]</value>
      <webElementGuid>4c8b1f7e-7d6e-485d-ba10-a447b32b45db</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
