<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__FileLocationDate</name>
   <tag></tag>
   <elementGuidId>690e4398-375c-45d4-b82f-448661191888</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#FileLocationDate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='FileLocationDate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>579a9202-6ee4-4cb4-8a9d-5b34f6069734</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>38f6f3f4-a2bd-4029-868d-d04862956f9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>0e39747e-bb17-4421-8cc4-934dec34e2ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-tns-c64-94 ui-inputtext ui-widget ui-state-default ui-corner-all ng-star-inserted</value>
      <webElementGuid>59d69f24-176d-43d5-b420-dd589ac37168</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>MM/DD/YYYY</value>
      <webElementGuid>ad13792a-6d00-47e3-9240-063b1de98bdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>FileLocationDate</value>
      <webElementGuid>51dcd457-707f-4934-84b8-fb3fe5b8b7f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>FileLocationDate</value>
      <webElementGuid>6dd1ac06-76a4-49dc-9855-809e8dcab2f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FileLocationDate&quot;)</value>
      <webElementGuid>89855d10-5044-4e18-a2a3-fb273c610828</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='FileLocationDate']</value>
      <webElementGuid>5ad987d5-2963-4092-aa61-d288fccc7673</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/div/div/app-case360/div[2]/div/div/div[2]/div/app-case360-file-tracking/roots-dialog/div/div[2]/app-case360-add-file-tracking/form/div/div/div[2]/div/roots-calendar/span/input</value>
      <webElementGuid>9be710b7-3b91-4634-a6e1-a6595bddec8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>4b493329-f48f-459b-a290-15fa14c18b49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'MM/DD/YYYY' and @id = 'FileLocationDate']</value>
      <webElementGuid>ccba0b3d-9af2-49b2-9321-e8bf9fe97467</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
