<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Event_Attachment_Save</name>
   <tag></tag>
   <elementGuidId>955db632-6049-4b3c-88b0-99f80061cb5b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@role='dialog']//div//app-add-dms-attachment-form//form//div//div//div//button[@type='submit'][normalize-space()='Save']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@role='dialog']//div//app-add-dms-attachment-form//form//div//div//div//button[@type='submit'][normalize-space()='Save']</value>
      <webElementGuid>a8df7572-e51b-43b1-badd-741830230629</webElementGuid>
   </webElementProperties>
</WebElementEntity>
