<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Pending_ml-2 fa-lg fas fa-chevron-circle-down</name>
   <tag></tag>
   <elementGuidId>84243111-d105-4698-8b55-dde3da3b0f98</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.ml-2.fa-lg.fas.fa-chevron-circle-down</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ui-panel-54-label']/div/div/roots-table/div/div/table/tbody/tr/td[5]/a/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>28995882-2557-43e5-8c22-3405f69c23c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ml-2 fa-lg fas fa-chevron-circle-down</value>
      <webElementGuid>e4c7d954-2bdd-4863-b53a-16e686fefafd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-panel-54&quot;)/div[@id=&quot;ui-panel-54-label&quot;]/div[@class=&quot;ui-panel-content ui-widget-content ng-tns-c76-197&quot;]/div[@class=&quot;app-tabview bg-white ng-tns-c76-197&quot;]/roots-table[1]/div[@class=&quot;ui-table ui-widget&quot;]/div[@class=&quot;ui-table-wrapper ng-star-inserted&quot;]/table[1]/tbody[@class=&quot;ui-table-tbody&quot;]/tr[@class=&quot;ng-star-inserted&quot;]/td[@class=&quot;expansion&quot;]/a[@class=&quot;font-weight-bold&quot;]/i[@class=&quot;ml-2 fa-lg fas fa-chevron-circle-down&quot;]</value>
      <webElementGuid>1747f2a7-f07c-44f0-827e-38cbdc2647ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ui-panel-54-label']/div/div/roots-table/div/div/table/tbody/tr/td[5]/a/i</value>
      <webElementGuid>28c6378b-9a7c-4d6d-9f7c-fd2b099fbc0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/a/i</value>
      <webElementGuid>565222c7-65c9-44f8-97e3-4b467f14d487</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
