<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__eventTime</name>
   <tag></tag>
   <elementGuidId>7990f6e4-ac76-4437-86a7-d52e36625ed9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#eventTime</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='eventTime']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fd115b41-f90c-434c-b94d-7f3badda746b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>81466ce4-f037-4ea5-a637-488eea0becca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>49620556-7cf5-4b7d-baa1-10157903531e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-tns-c64-184 ui-inputtext ui-widget ui-state-default ui-corner-all ng-star-inserted</value>
      <webElementGuid>79a5c802-d54e-4687-b7ef-e9cab5f8d800</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>HH:MM AM/PM</value>
      <webElementGuid>c0dcc181-937b-4aae-b697-7e7322890486</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>eventTime</value>
      <webElementGuid>07ef44a0-226c-4d15-ae05-0c9397bfae10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>eventTime</value>
      <webElementGuid>4ff87fa4-447e-40d8-852e-3f831957066c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;eventTime&quot;)</value>
      <webElementGuid>a18b0fc6-656f-40fa-ae71-aad921bc547f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='eventTime']</value>
      <webElementGuid>315f27c5-eae0-4724-b06e-1a2a81a2ebe5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/div/div/app-case360/div[2]/div/div/div[2]/div/app-event-information/div/app-case360-events/div/app-addcase360-events/div/form/div[2]/div/div/div[5]/div/roots-calendar/span/input</value>
      <webElementGuid>755d05be-daf0-4715-a456-69b8ae37c6a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/roots-calendar/span/input</value>
      <webElementGuid>ce84cc69-761d-45a7-bca8-32dde218dfc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'HH:MM AM/PM' and @id = 'eventTime']</value>
      <webElementGuid>c96716b5-3dd2-482e-8fec-35648b5f9b28</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
