<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__resultDate</name>
   <tag></tag>
   <elementGuidId>c9387c52-84b5-412d-9a4c-b4af4ee12d77</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#resultDate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='resultDate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>499e9ca8-b96a-41d5-a2f9-40a875c9e4b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>aa64e7f0-d917-4bb6-927e-a77a8a0917a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>81624e90-17f7-4d22-a6b9-02ff0a84c42a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-tns-c64-189 ui-inputtext ui-widget ui-state-default ui-corner-all ng-star-inserted</value>
      <webElementGuid>42ebe21b-21cb-4260-9b32-ebd21500991a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>MM/DD/YYYY</value>
      <webElementGuid>7905f659-23ee-40ad-b27d-d209e3694a47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>resultDate</value>
      <webElementGuid>7d35de95-7bee-44b1-9180-e7d5ba2a398c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>resultDate</value>
      <webElementGuid>dec1a38c-3f05-424b-99b8-78ce8320b95b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;resultDate&quot;)</value>
      <webElementGuid>9f34f157-298b-4249-9099-42ba4209fe30</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='resultDate']</value>
      <webElementGuid>0cdaa127-36cb-4f09-98c3-6a66c20f6bed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/div/div/app-case360/div[2]/div/div/div[2]/div/app-event-information/div/app-case360-events/div/app-addcase360-events/div[2]/div/div/app-addcase360-events-results/roots-dialog/div/div[2]/form/div/div/div/div/div[2]/div/roots-calendar/span/input</value>
      <webElementGuid>ce18d7aa-98c8-433e-aa6e-865daaa32e5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/roots-calendar/span/input</value>
      <webElementGuid>4eb145f8-cd8d-43e2-9d7a-0571f024f65f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'MM/DD/YYYY' and @id = 'resultDate']</value>
      <webElementGuid>e9d4e9e0-cd35-478a-8e28-8a9ac99aed90</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
