<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Case</name>
   <tag></tag>
   <elementGuidId>8a69a6a6-21d3-4a19-a66c-fe1828a7514c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='search']/div/div/div/div/div/div/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.p-0.text-grayPrimaryColor.white-space-nowrap</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6253ee64-051b-45ac-8941-7672cf2deceb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>132076b7-691d-4217-9782-832befdc6232</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>38ed5c5c-ebc6-4f1f-91a0-0529b44d2bb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>1ca1d068-2b30-4c46-a8e0-95be01530e0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>32ebf70e-98c2-4f9c-9588-c685fd5434bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a843b5bb-823a-4d93-979f-29d1abe63404</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-0 text-grayPrimaryColor white-space-nowrap</value>
      <webElementGuid>7da4b525-c086-40a3-bea4-f57cf9a49b97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Case # </value>
      <webElementGuid>27396109-0653-45db-a2b7-2bfa97894c8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search&quot;)/div[@class=&quot;advancsSearchBody d-flex align-items-center align-items-stretch bg-white animated fadeInDown faster&quot;]/div[@class=&quot;col align-self-center d-flex align-items-center h-100 animated fadeInDown faster&quot;]/div[@class=&quot;searchDropdown ng-star-inserted show&quot;]/div[@class=&quot;maga-menu dropdown-menu p-3 rounded show&quot;]/div[@class=&quot;d-flex&quot;]/div[@class=&quot;flex-column menuspace&quot;]/div[@class=&quot;ng-star-inserted&quot;]/a[@class=&quot;p-0 text-grayPrimaryColor white-space-nowrap&quot;]</value>
      <webElementGuid>ef01d58f-6394-4d84-968f-41526f1f5904</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='search']/div/div/div/div/div/div/div/a</value>
      <webElementGuid>9f8869af-d593-4b5c-a425-eb4f1d40caf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Case #')]</value>
      <webElementGuid>784834dc-6581-4a58-b122-df89f4f8a93b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Press Enter to open the Dialog box and then use navigation keys to navigate'])[3]/following::a[2]</value>
      <webElementGuid>9538bbf4-052e-4723-9af2-2d523b555226</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='balya I, Pradeep kumar'])[1]/following::a[2]</value>
      <webElementGuid>6d20f13b-686b-4a3e-9e16-a080de467546</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='label for searchText'])[1]/preceding::a[12]</value>
      <webElementGuid>1ceee567-a829-4a7d-b36e-063cd671f222</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No Results Found'])[1]/preceding::a[12]</value>
      <webElementGuid>74245821-9a3a-4dc3-a79b-bab702d5e07b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Case #']/parent::*</value>
      <webElementGuid>45c5040b-da0a-46da-ac09-b9303a7f3968</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[9]</value>
      <webElementGuid>ea2f062b-7574-4dae-9b24-4672d96a0890</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/a</value>
      <webElementGuid>522e5037-c668-490d-9324-be0ed8bf0c42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = ' Case # ' or . = ' Case # ')]</value>
      <webElementGuid>fbb9c3e4-bdf9-4072-b52d-ba2bf83a8eb1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
