<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Name</name>
   <tag></tag>
   <elementGuidId>ba0c472a-35b3-4d36-bc23-1f44219c9de2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='navbarDropdown']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#navbarDropdown</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>81a73d18-2fdf-4ab5-a864-d648ac736a83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>a69f9bea-e354-4e48-a805-78aea5164d88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>navbarDropdown</value>
      <webElementGuid>fd6138e2-ba1a-4354-a4ca-8fb0317c5b11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e18d00dc-20de-4909-a854-4a5a1eb78561</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>b8d61b05-ce0f-4e4d-ad38-7997bda24a12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f79d3c76-310d-4ab6-a7e6-c6af1cd4fb5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>590e78f1-5ade-4d2a-9b54-bf12192de07e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link dropdown-toggle text-secondary font-weight-bold mr-1</value>
      <webElementGuid>607bdd01-53b4-4c20-a299-9f2a341a4454</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Name </value>
      <webElementGuid>ef100261-0ba1-48c1-bab6-c31622f98f9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search&quot;)/div[@class=&quot;advancsSearchBody d-flex align-items-center align-items-stretch bg-white animated fadeInDown faster&quot;]/div[@class=&quot;col align-self-center d-flex align-items-center h-100 animated fadeInDown faster&quot;]/div[@class=&quot;searchDropdown ng-star-inserted&quot;]/a[@id=&quot;navbarDropdown&quot;]</value>
      <webElementGuid>0b4ba7f5-1521-43aa-a3d9-fad87215158c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='navbarDropdown']</value>
      <webElementGuid>78d5ffb5-b152-4a95-99d4-cd8c413a6f6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='search']/div/div/div/a</value>
      <webElementGuid>35b6ba32-ac4f-4510-b56e-1afcf8345756</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Name')]</value>
      <webElementGuid>7649d98a-eed2-4fe3-aa2e-82b31d4fa232</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Press Enter to open the Dialog box and then use navigation keys to navigate'])[3]/following::a[1]</value>
      <webElementGuid>cf4258c9-9e66-48ec-809f-46485719bf51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='balya I, Pradeep kumar'])[1]/following::a[1]</value>
      <webElementGuid>f8b01018-25d5-4b33-a0a3-181910a07b31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='label for searchText'])[1]/preceding::a[13]</value>
      <webElementGuid>245accc7-8566-4f19-a4d3-99b72a3453a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No Results Found'])[1]/preceding::a[13]</value>
      <webElementGuid>924860b3-10ef-420a-b9e0-0613780454ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Name']/parent::*</value>
      <webElementGuid>ff1c7b44-0150-4875-a82b-dd3234178ed2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[8]</value>
      <webElementGuid>cd522092-7b03-4dfe-ba60-38f58bf7177b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/a</value>
      <webElementGuid>0d80fac4-1df9-471c-a240-6d65986bafbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @id = 'navbarDropdown' and (text() = ' Name ' or . = ' Name ')]</value>
      <webElementGuid>f938f1d7-f4ce-4174-b26c-46f9269c2676</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
