<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Press Enter to open the Dialog box and th_4630ec</name>
   <tag></tag>
   <elementGuidId>3aab4bb1-fe66-4a72-be33-90263526f5ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//i[@id='searchMenuIcon']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#searchMenuIcon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>8e69904e-8f80-46ac-a5d9-f0f8b500e28d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>799889f1-543b-42b7-96cc-8927616886e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>searchMenuIcon</value>
      <webElementGuid>cf7581df-0549-4a9b-8db6-635a85132477</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-lg fa-search mr-2 align-self-center cursor-pointer</value>
      <webElementGuid>4c368ea0-c0b1-4fc6-a23f-87233d72211f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchMenuIcon&quot;)</value>
      <webElementGuid>21b944e0-8d2d-4080-8af1-cdcfbdae72ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//i[@id='searchMenuIcon']</value>
      <webElementGuid>e3e828c1-bf7e-486c-a404-baf04ed07e0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navbarSupportedContent']/ul/li[5]/a/i</value>
      <webElementGuid>f9378ed1-1ca6-47cf-8fe4-27901b8c64b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/a/i</value>
      <webElementGuid>cfa8c9fc-41c3-44dc-88df-e98191dec7a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[@id = 'searchMenuIcon']</value>
      <webElementGuid>55ba1bed-202f-427b-9f6d-6c38caad4138</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
