<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>757c3fc2-ac27-484b-bf89-14d26d01ab65</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;crimes-logo&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='header']/app-header/nav/div/a/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>3ca37890-8b22-408f-b20d-f1e1a65ea0c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>crimes-logo</value>
      <webElementGuid>a0903a40-4787-4bc7-ada5-7340efa079fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>assets/images/CMP_Logo_Cloud.png</value>
      <webElementGuid>cb253efb-c9c2-466a-811e-6fcba0580998</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)/app-header[1]/nav[@class=&quot;navbar navbar-expand-lg navbar-light py-0&quot;]/div[@class=&quot;position-relative row w-100&quot;]/a[@class=&quot;navbar-brand mr-0 col-lg-4 col-xl-3&quot;]/div[@class=&quot;d-flex align-items-center h-100 animated bounceIn delay-0.5s cursor-default&quot;]/div[@class=&quot;mr-2 cursor-pointer&quot;]/img[1]</value>
      <webElementGuid>79b4b538-e70a-4365-827b-1eefb145da19</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='header']/app-header/nav/div/a/div/div/img</value>
      <webElementGuid>0ca0277f-ffde-442a-8d6d-9dd1ed8a76b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='crimes-logo']</value>
      <webElementGuid>1189e8df-021c-4870-8265-f7c6e2fb409a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>34ec7d6e-8149-4f4a-9ea1-35f2aede123a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'crimes-logo' and @src = 'assets/images/CMP_Logo_Cloud.png']</value>
      <webElementGuid>edd52812-024f-47c2-b100-3f95ec09470d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
