<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_label for searchText_Search</name>
   <tag></tag>
   <elementGuidId>8a758e69-e79c-4bbc-8bd7-0a5b4ccc6721</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Search']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Search</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6c30c88d-a66e-40b8-a913-c04de00b161a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>ae8295d2-1a11-4686-ad09-e6d30ab6ee0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>abdd43f2-13af-4a26-a25a-05af2762fdd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>cce858a3-8944-4041-98ef-601388e585b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>9a2525cf-0554-4387-ae26-96ca8331a98a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>py-1 pr-2 h-100 form-control search-box ng-untouched ng-valid ng-dirty</value>
      <webElementGuid>99174a4e-9a2a-463d-a5c4-48770b699921</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Search&quot;)</value>
      <webElementGuid>1c1ab45d-179a-49ae-b7dc-e636b76dee70</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Search']</value>
      <webElementGuid>c78f0e0f-f407-4500-9765-b6a46cc5577e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='search']/div/div/input</value>
      <webElementGuid>fc0cbc68-39d3-4f8f-a702-3d82c1edf12d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>e096b3bb-b013-4430-8490-ec06dbd6ce43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'search' and @id = 'Search' and @name = 'Search' and @placeholder = 'Search']</value>
      <webElementGuid>17f68529-2e32-4b46-88ac-77d9405f5c5e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
