<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Edit</name>
   <tag></tag>
   <elementGuidId>17878785-733a-472e-913b-d52f23ca673b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ml-auto.mr-5.editIcon.text-right.ng-star-inserted > button.font-weight-bold.mr-3.text-primary.mb-md-0.mb-0.p-0.border-0.bg-transparent.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ui-panel-12']/div/roots-header/div/div[2]/button</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Edit ' or . = 'Edit ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9d9118e3-a6ac-44e3-9c0c-e5d9f6f012eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>font-weight-bold mr-3 text-primary mb-md-0 mb-0 p-0 border-0 bg-transparent ng-star-inserted</value>
      <webElementGuid>54cda72a-2d48-4ef0-9a5e-7c918c318941</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Edit </value>
      <webElementGuid>3d7c07d0-920d-4f16-888d-9ea1cde2cee4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-panel-12&quot;)/div[@class=&quot;ng-tns-c76-110 ui-panel-titlebar ui-widget-header ui-helper-clearfix ui-corner-all ng-star-inserted&quot;]/roots-header[@class=&quot;w-100 ng-tns-c76-110&quot;]/div[@class=&quot;d-flex&quot;]/div[@class=&quot;ml-auto mr-5 editIcon text-right ng-star-inserted&quot;]/button[@class=&quot;font-weight-bold mr-3 text-primary mb-md-0 mb-0 p-0 border-0 bg-transparent ng-star-inserted&quot;]</value>
      <webElementGuid>5636eec8-fee1-488f-8804-bf6dd3e3c18e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ui-panel-12']/div/roots-header/div/div[2]/button</value>
      <webElementGuid>fa75e958-698c-4a58-94ba-512b78e9b6ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Case Information'])[1]/following::button[1]</value>
      <webElementGuid>7d1c50bb-1420-4965-859c-aa616f0b8b1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Detail'])[2]/following::button[1]</value>
      <webElementGuid>3436ecf9-9802-444b-929b-48e857ec57cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[1]/preceding::button[1]</value>
      <webElementGuid>34a95779-041f-40ae-bd14-1d373836cf90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Is Sensitive Case'])[1]/preceding::button[2]</value>
      <webElementGuid>69c16c75-db41-440d-b64e-7e19f07cd19d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Edit']/parent::*</value>
      <webElementGuid>99fde379-5565-4a36-8897-be7ef1d99c25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>c35f82f4-29de-4347-95ee-bc8c26b41895</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Edit ' or . = 'Edit ')]</value>
      <webElementGuid>490a8f2e-c787-4b15-8f07-e0a75976b407</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
