<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Search</name>
   <tag></tag>
   <elementGuidId>372ed21b-a751-4e3c-b725-46cd89b5367c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-white.border-primary.mr-2.ui-button.ui-widget.ui-state-default.ui-corner-all.ui-button-text-icon-left</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[11]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7c779701-5241-4aa4-a2c9-662236033477</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>600b339a-40e5-413c-aedc-95c55ac779e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>icon</name>
      <type>Main</type>
      <value>fa fa-search-plus</value>
      <webElementGuid>2a81b348-c1ad-4f37-bde1-052646831912</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>label</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>520d219e-ae80-4bc8-87d3-377b794ef515</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-white border-primary mr-2 ui-button ui-widget ui-state-default ui-corner-all ui-button-text-icon-left</value>
      <webElementGuid>e3abb86f-8a9f-4c57-9ed7-ed924e0a3318</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>8c05fe70-2e77-44f4-a082-90304e25d89c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-panel-19&quot;)/div[@id=&quot;ui-panel-19-label&quot;]/div[@class=&quot;ui-panel-content ui-widget-content ng-tns-c76-154&quot;]/div[@class=&quot;container-fluid my-3 ng-tns-c76-154&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-8&quot;]/button[@class=&quot;btn btn-white border-primary mr-2 ui-button ui-widget ui-state-default ui-corner-all ui-button-text-icon-left&quot;]</value>
      <webElementGuid>65b7289b-784a-462c-98b1-e5e05f20d54e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[11]</value>
      <webElementGuid>e75d4a6b-dba7-4509-a67d-79d824ecc83e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ui-panel-19-label']/div/div/div/div[2]/button</value>
      <webElementGuid>1e65695c-09ea-4468-be7a-ff66aea356a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Keyword'])[1]/following::button[1]</value>
      <webElementGuid>36c97763-2dcc-418d-bf09-da247956dd2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Keywords Search Criteria'])[1]/following::button[1]</value>
      <webElementGuid>24b76d00-057d-471a-a8cd-fb923e083095</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/button</value>
      <webElementGuid>fea716ef-bd8f-4b3b-8f48-3b23cd46c34c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Search' or . = 'Search')]</value>
      <webElementGuid>838d52ee-63bf-4afe-a1c6-434e3ba8abf3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
