<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Keywords</name>
   <tag></tag>
   <elementGuidId>1a0e6850-1296-4df3-941b-21d3e6d6584d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>roots-header.w-100.ng-tns-c76-138 > div.d-flex.align-items-center > div.font-weight-bold.text-black</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;ui-panel-39&quot;]/div[1]/roots-header/div/div</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//div[normalize-space()='Keywords']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>12290881-c947-4a21-b914-8027fb093bc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>font-weight-bold text-black</value>
      <webElementGuid>901eec39-213a-4897-879a-150f03440992</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Keywords</value>
      <webElementGuid>044dc64e-d953-43fe-994d-8368e18880e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[normalize-space()='Keywords']</value>
      <webElementGuid>9d7cc13a-6b2b-4210-964c-334ea66110eb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ui-panel-17']/div/roots-header/div/div</value>
      <webElementGuid>cbce46e7-562d-4d02-9c8f-f2448539516f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Type:'])[2]/following::div[6]</value>
      <webElementGuid>e8b9667e-78de-469f-8ced-65a7a1f96a43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description:'])[2]/following::div[7]</value>
      <webElementGuid>96bc3ce2-8f0d-40a0-a2f7-4d92072f41f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Keywords'])[1]/preceding::div[1]</value>
      <webElementGuid>94bb4a74-b6e3-44c2-a029-0010a6c5cd13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Keywords']/parent::*</value>
      <webElementGuid>593bbb33-82f7-426a-bd55-26d364a9cd28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-key-words/div/roots-panel/div/div/roots-header/div/div</value>
      <webElementGuid>2deaad6a-a2e0-4dd0-b585-81003e4dcab4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Keywords' or . = 'Keywords')]</value>
      <webElementGuid>4a703028-1e35-4926-91f4-ece6f7d4ef8a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
