<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Keyword_keyWord</name>
   <tag></tag>
   <elementGuidId>23fca774-d30b-4a13-bfe4-d126dd256166</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#keyWord</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='keyWord']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c709f6cc-e52d-41c9-b3fa-3c050776fea1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>keyWord</value>
      <webElementGuid>eae4291f-e8aa-4876-b972-9bfa903f8b9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search...</value>
      <webElementGuid>ca9de158-5072-484c-86c6-dba276888d27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>24a727dc-be85-4ec8-aca3-011d1641bb27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ml-3 ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>fa4d72fb-2738-4d15-a22c-4b0e47711ff9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;keyWord&quot;)</value>
      <webElementGuid>2184d78e-b47a-4f6b-8081-81afa6b6ccf4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='keyWord']</value>
      <webElementGuid>5e2e9054-d69e-4627-a826-656843b2b77c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ui-panel-19-label']/div/div/div/div/div/input</value>
      <webElementGuid>26d74ba4-d8dd-4b5b-af1b-659f673ebc7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/input</value>
      <webElementGuid>58327e89-dc0f-49d2-b4f5-4eaf3b2ef516</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'keyWord' and @placeholder = 'Search...' and @type = 'text']</value>
      <webElementGuid>b986b578-af53-41f7-ba4d-2131d3f0616a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
