<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_New Case Identifier</name>
   <tag></tag>
   <elementGuidId>3571a431-3578-4304-bb77-6788421ca198</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.ui-dropdown-item.ui-corner-all</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main']/div/div/app-case360/div[2]/div/div/div[2]/div/app-case360-details/div[2]/div[4]/app-case-detail/form/roots-dialog/div/div[2]/div/div/div/div/roots-dropdown/div/div[5]/div/ul/roots-dropdownitem/li</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;main&quot;]/div/div/app-case360/div[2]/div/div/div[2]/div/app-case360-details/div[2]/div[4]/app-case-detail/form/roots-dialog/div/div[2]/div/div/div[1]/div/roots-dropdown/div/div[5]/div/ul/roots-dropdownitem/li/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>5c54fc7e-2a52-45a9-84b5-78e9e63c181d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>38b87907-74ff-426f-beb7-e0ee235cde2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>New Case Identifier</value>
      <webElementGuid>2a7bda3a-eda0-4ea0-a059-14d4d40f3112</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-dropdown-item ui-corner-all</value>
      <webElementGuid>814e6516-b22d-4352-a4e0-150ee667282c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>New Case Identifier</value>
      <webElementGuid>44963858-882c-49be-acfd-bb2cf7497cc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;main&quot;]/div/div/app-case360/div[2]/div/div/div[2]/div/app-case360-details/div[2]/div[4]/app-case-detail/form/roots-dialog/div/div[2]/div/div/div[1]/div/roots-dropdown/div/div[5]/div/ul/roots-dropdownitem/li/span</value>
      <webElementGuid>0e7679f8-7728-4e98-924a-30b6406f7daf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/div/div/app-case360/div[2]/div/div/div[2]/div/app-case360-details/div[2]/div[4]/app-case-detail/form/roots-dialog/div/div[2]/div/div/div/div/roots-dropdown/div/div[5]/div/ul/roots-dropdownitem/li</value>
      <webElementGuid>b4828310-7925-4b2d-94d8-ef3eea54dc1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select'])[14]/following::li[1]</value>
      <webElementGuid>f0b045ae-1711-4237-b98b-f51d90f169b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[5]/following::li[1]</value>
      <webElementGuid>e58a33a8-2b81-4c03-b6c4-66cc1b052898</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Case Detail Type is required.'])[1]/preceding::li[1]</value>
      <webElementGuid>f309911e-7554-4af6-baea-8ad04617f4f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//roots-dropdownitem/li</value>
      <webElementGuid>f8ad74a3-dda4-45e2-afc7-c19a3f371c50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'New Case Identifier' or . = 'New Case Identifier')]</value>
      <webElementGuid>ff714aea-bc35-4ffc-b747-56bdda329f38</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
