<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Select_ui-dropdown-trigger-icon ui-cli_8cbf32</name>
   <tag></tag>
   <elementGuidId>a17efa68-67bf-44e2-9874-3307b087b631</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>
//roots-dropdown[@inputid='AssignedStaff']//div//div//label[contains(text(),'Select')]
</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.ui-dropdown-trigger-icon.ui-clickable.ng-tns-c50-124.fas.fa-angle-down</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main']/div/div/app-case360/div[2]/div/div/div[2]/div/app-case360-details/div[2]/div[3]/app-assigned-staff/roots-dialog/div/div[2]/form/div/div/div[3]/div/roots-dropdown/div/div[4]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>931c1f95-ceaa-4806-86b5-40ac540ee3e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-dropdown-trigger-icon ui-clickable ng-tns-c50-124 fas fa-angle-down</value>
      <webElementGuid>c7c4f372-9c4c-44b5-9dc8-bb8ad7c9c833</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>
//roots-dropdown[@inputid='AssignedStaff']//div//div//label[contains(text(),'Select')]
</value>
      <webElementGuid>70a1a738-972a-4661-a11a-b87393eaee3a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/div/div/app-case360/div[2]/div/div/div[2]/div/app-case360-details/div[2]/div[3]/app-assigned-staff/roots-dialog/div/div[2]/form/div/div/div[3]/div/roots-dropdown/div/div[4]/span</value>
      <webElementGuid>3a9e67c3-8cb8-49e1-9f18-664f08cf90ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/form/div/div/div[3]/div/roots-dropdown/div/div[4]/span</value>
      <webElementGuid>a92ddbaf-9fbd-43e6-bd3b-1e4d87124f78</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
