<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Case Summary_form-control ng-untou_92d3db</name>
   <tag></tag>
   <elementGuidId>d65bdeae-76fc-449e-a0ac-14f7c8138c67</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>textarea.form-control.ng-untouched.ng-valid.ng-dirty</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@type='text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>dd1f0377-e136-4837-8ccd-cff289123d57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f4ec55db-30a2-40e5-af00-b3e1d5586d78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Type here</value>
      <webElementGuid>1a06f514-edc8-4130-b7e7-2116fd2cad23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>d35659dc-c41d-42d4-9c6c-43d3e4c3d66e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>e194eb28-6ef8-4bf0-8b80-5a892cae30b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>CaseNotes</value>
      <webElementGuid>c8b31d59-f924-40dd-a3b4-758f9c40a72b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>CaseNotes</value>
      <webElementGuid>298a4d6e-c5b3-40bb-9b48-fa4ff513878a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-valid ng-dirty</value>
      <webElementGuid>841c5e69-c94d-4361-b388-96ec3f7e5659</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f4d436af-2516-42aa-bb51-cf164e4f3b8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-panel-12&quot;)/div[@id=&quot;ui-panel-12-label&quot;]/div[@class=&quot;ui-panel-content ui-widget-content ng-tns-c76-110&quot;]/form[@class=&quot;ng-tns-c76-110 ng-untouched ng-valid ng-dirty&quot;]/div[@class=&quot;detail-tab&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12 ng-star-inserted&quot;]/div[@class=&quot;form-group&quot;]/textarea[@class=&quot;form-control ng-untouched ng-valid ng-dirty&quot;]</value>
      <webElementGuid>36a37c19-a05d-4c3e-8ef9-09fd2b27a979</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@type='text']</value>
      <webElementGuid>7aa29118-8432-485b-904b-1631581f6c5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ui-panel-12-label']/div/form/div[2]/div/div[11]/div/textarea</value>
      <webElementGuid>2dbd79fd-e80a-4f61-bfbf-dd6aaa1c0114</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>592bfaf6-1c2d-47f6-9f6f-d078bc339f39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@type = 'text' and @placeholder = 'Type here']</value>
      <webElementGuid>b753d46d-f579-4590-9006-0da7ff3bf044</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
