<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Delete</name>
   <tag></tag>
   <elementGuidId>b2e771a7-5d2f-42a9-a3c7-b1ff23a0b2c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main']/div/div/app-case360/div[2]/div/div/div[2]/div/app-case360-notes/div[3]/app-notes/div/roots-cardview/div/div/div/div[2]/button[2]/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fa-md.fas.fa-trash-alt</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>0ee79421-3094-4745-b2ae-ea0e8acf2cba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Delete</value>
      <webElementGuid>623b0ca4-fba0-4d83-ace3-fcb0b7f89d3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa-md fas fa-trash-alt</value>
      <webElementGuid>1e5ec28c-187d-426d-9ccf-79429fb5bb1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Delete</value>
      <webElementGuid>d0ec2751-9260-429d-bad6-f50633c57263</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;bg-white min-height-600&quot;]/div[@class=&quot;bg-E3E3E3&quot;]/app-case360[@class=&quot;ng-star-inserted&quot;]/div[2]/div[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-9 col-xl-9 mb-3 mb-lg-0 pl-lg-0 pl-xl-0&quot;]/div[@class=&quot;clearfix h-100 bg-white&quot;]/app-case360-notes[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;container-fluid pb-3&quot;]/app-notes[1]/div[@class=&quot;pb-3 ng-star-inserted&quot;]/roots-cardview[1]/div[@class=&quot;roots-card-template&quot;]/div[@class=&quot;roots-card-header add-border&quot;]/div[@class=&quot;main-card-container&quot;]/div[@class=&quot;dflex ml-auto ng-star-inserted&quot;]/button[@class=&quot;text-primary ml-2 button-class ng-star-inserted&quot;]/i[@class=&quot;fa-md fas fa-trash-alt&quot;]</value>
      <webElementGuid>b6e2e3d9-a205-4721-bbb8-cebd152b0fcc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/div/div/app-case360/div[2]/div/div/div[2]/div/app-case360-notes/div[3]/app-notes/div/roots-cardview/div/div/div/div[2]/button[2]/i</value>
      <webElementGuid>136729bf-878d-48f3-90c0-b26488184d5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='edit'])[1]/following::i[1]</value>
      <webElementGuid>68360ec5-e317-4941-afb0-03aa3c41b8ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notes'])[3]/preceding::i[1]</value>
      <webElementGuid>b95acae2-bb07-4b1d-b5ee-93ac8b6fc855</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button[2]/i</value>
      <webElementGuid>3b83f43a-8259-4e3f-8ecf-767b61f4e15b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[@title = 'Delete' and (text() = 'Delete' or . = 'Delete')]</value>
      <webElementGuid>eea31dea-ce41-4949-8cb4-f039076e9580</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
