<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Costs</name>
   <tag></tag>
   <elementGuidId>5528c1bc-0bc6-4231-8332-7dec2b45a4ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//roots-scrollpanel[@id='sideBar']/div/div/div/ul/li[4]/div/label/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>73bdf367-0210-4a36-b4ce-9c1d2025601d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#/home/case360/3818/costs</value>
      <webElementGuid>4d0d69df-bcfd-46d2-8b10-b39ab1d6f420</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-primary</value>
      <webElementGuid>fcd51422-c7b3-4923-946d-34a9eccb038a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Costs</value>
      <webElementGuid>2c2b149d-ae2c-478a-8e22-cc2acd23e300</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sideBar&quot;)/div[@class=&quot;custom-sideBar ui-scrollpanel ui-widget ui-widget-content ui-corner-all&quot;]/div[@class=&quot;ui-scrollpanel-wrapper&quot;]/div[@class=&quot;ui-scrollpanel-content&quot;]/ul[@class=&quot;border-top ng-star-inserted&quot;]/li[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;d-flex align-items-center my-2 mx-3&quot;]/label[@class=&quot;mb-0 ng-star-inserted&quot;]/a[@class=&quot;text-primary&quot;]</value>
      <webElementGuid>16cac667-c79a-4ec1-a279-5049d8f2e441</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//roots-scrollpanel[@id='sideBar']/div/div/div/ul/li[4]/div/label/a</value>
      <webElementGuid>522768b8-e9c6-427f-a40e-7582e829f5ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Costs')]</value>
      <webElementGuid>ac622119-3a7a-449e-a4ea-42ad22924b07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Case Charges'])[1]/following::a[1]</value>
      <webElementGuid>e59c89ca-d830-41e4-b306-964aa6066979</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Participants'])[1]/following::a[2]</value>
      <webElementGuid>8f2002af-c202-41a5-8089-8f0ef32a617a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Detail'])[1]/preceding::a[1]</value>
      <webElementGuid>185ff8bf-e456-4d07-a694-cae516f4bb95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Documents'])[1]/preceding::a[2]</value>
      <webElementGuid>54494e37-4016-41fd-a152-1c566578a3e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Costs']/parent::*</value>
      <webElementGuid>045324de-d64c-4bee-a3e3-64bfad4975b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#/home/case360/3818/costs')]</value>
      <webElementGuid>03bccbb6-fde1-433d-bcbe-cf1bdd61eb08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/div/label/a</value>
      <webElementGuid>136d458e-d807-445e-8e85-3ae9ab448176</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#/home/case360/3818/costs' and (text() = 'Costs' or . = 'Costs')]</value>
      <webElementGuid>f0cdfd87-02a1-42c9-99c0-240afd351a69</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
