<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__Amount</name>
   <tag></tag>
   <elementGuidId>c27a4345-8846-456c-b571-8efb28aff3e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Amount</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Amount']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e2a56d22-e3bf-4064-b968-6f51abd5cbba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>db341864-fa89-4c5b-afc2-94bc55d68875</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Amount</value>
      <webElementGuid>2a9a9386-b346-4da0-b003-d4fb7083ac7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>Amount</value>
      <webElementGuid>5ae042cd-9d64-476b-bade-213216bcfc0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>1c4ba30b-d9a4-44a5-b7a2-accfbb627e71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>roots-keyfilter</name>
      <type>Main</type>
      <value>num</value>
      <webElementGuid>6f4cafba-8266-4b44-8891-57497ab7eedf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Type Here</value>
      <webElementGuid>96608448-aede-4618-b937-8333af903a61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>b112b2ad-ebec-4da7-be19-df85596bb236</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Amount&quot;)</value>
      <webElementGuid>38f8d4ed-fd66-46b5-9dd2-5e0a24217a67</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Amount']</value>
      <webElementGuid>b32cec4b-48b2-481b-a8bf-1e8b93e2eb9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/div/div/app-case360/div[2]/div/div/div[2]/div/app-case360-cost/div[3]/div[2]/roots-dialog/div/div[2]/div/app-addcase360-costs/form/div/div/div[2]/div/input</value>
      <webElementGuid>b3042e11-73ad-459a-be1c-71a7d2267817</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>268fe17a-17e0-4efb-9d5c-079b7b0ee141</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'Amount' and @placeholder = 'Type Here']</value>
      <webElementGuid>7532f05d-3117-4bdc-b7e5-0577ccf93736</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
