<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Payee_Payee</name>
   <tag></tag>
   <elementGuidId>eff3090f-2170-4b79-9142-fde74121e9cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Payee</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Payee']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d1eb0bc2-1177-4fc8-ad91-06fdf9f76030</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>02703ac7-5997-411f-bbf4-0f87ab802cb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Payee</value>
      <webElementGuid>74050f01-5235-40ba-8e8f-8b4cc93e549a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>Payee</value>
      <webElementGuid>55920a98-3aad-453b-bb6a-af47e4f848cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>8f10e8f0-570c-4dea-8c36-ac97151d59ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Type Here</value>
      <webElementGuid>bff4606c-c81c-4646-aa50-7484e3a01abc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>5a020a70-b657-4d0b-b94c-b2269361fac3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Payee&quot;)</value>
      <webElementGuid>12d2d408-017e-4cce-a06f-60784beded5a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Payee']</value>
      <webElementGuid>ddee5dbe-574d-474a-96c5-f9406c407f6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/div/div/app-case360/div[2]/div/div/div[2]/div/app-case360-cost/div[3]/div[2]/roots-dialog/div/div[2]/div/app-addcase360-costs/form/div/div[2]/input</value>
      <webElementGuid>b695c230-2ead-45c1-9508-a65b4f0cdd92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[2]/input</value>
      <webElementGuid>c6125c15-d506-4451-a6aa-fba12e41fa22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'Payee' and @placeholder = 'Type Here']</value>
      <webElementGuid>decdcff6-4962-4d5b-9038-608da658bcd7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
