<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Invoice_InvoiceNum</name>
   <tag></tag>
   <elementGuidId>df45efc5-ba33-4584-b585-40d21fc3a5bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#InvoiceNum</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='InvoiceNum']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>62e0be0c-8a1c-4f5b-b869-99bd652911b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9bec55c8-ba1e-455e-9d72-d691d037fe5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>InvoiceNum</value>
      <webElementGuid>40aac05e-a968-4fd8-9505-4d4fe6e2b961</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>InvoiceNum</value>
      <webElementGuid>68d192f5-9250-41f8-98b5-796f3ea0e7f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>507dc181-ca9a-446e-adfd-ea182c0e8361</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Type Here</value>
      <webElementGuid>266c0a5f-a35b-4966-bec8-b84c56e8c279</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>79b62818-68d4-4177-9114-de1cd2cd6902</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;InvoiceNum&quot;)</value>
      <webElementGuid>f1132fcc-eadb-4982-b397-acff0f06a2b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='InvoiceNum']</value>
      <webElementGuid>fec4bc44-f7c3-4cde-bdeb-5a45c1a4df11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/div/div/app-case360/div[2]/div/div/div[2]/div/app-case360-cost/div[3]/div[2]/roots-dialog/div/div[2]/div/app-addcase360-costs/form/div/div[3]/div[2]/div/input</value>
      <webElementGuid>54043c22-42da-4799-a77d-d2fa543e1126</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/input</value>
      <webElementGuid>93bc3f37-8fff-4e7b-9829-22ffbe5fcf19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'InvoiceNum' and @placeholder = 'Type Here']</value>
      <webElementGuid>cc7f467b-0472-446c-9646-6ac20ae55cf4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
