<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Notes_Note</name>
   <tag></tag>
   <elementGuidId>cdcdfb04-7548-4717-bb3c-c5022a9c2509</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Note</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='Note']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>ae01d791-dbda-4f6a-a2e4-b5b19cea8370</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>9d02336a-e18f-41a7-b450-a978e84c0132</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>b5bf31b5-76ab-4696-8e2b-0be7fc7a260b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Note</value>
      <webElementGuid>5cbb5657-bd48-49cd-9e8f-2d24ce2d5b0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>5000</value>
      <webElementGuid>64edb25e-5c05-4e22-a4ec-3a4503ebaaf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>Note</value>
      <webElementGuid>d2482b60-80e1-4ecb-8f2d-5048f4d4b971</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-valid ng-dirty</value>
      <webElementGuid>1d84ddb5-b5dc-4d81-a3e7-78899b510d68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8687bf99-f84b-4bcf-83ee-790257e31990</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Note&quot;)</value>
      <webElementGuid>dd88c956-0ec1-4ff0-9e5c-8f1cd7e0d233</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='Note']</value>
      <webElementGuid>f8826e8d-2a86-431c-b051-5c6fd9831010</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/div/div/app-case360/div[2]/div/div/div[2]/div/app-case360-cost/div[3]/div[2]/roots-dialog/div/div[2]/div/app-addcase360-costs/form/div/div[4]/textarea</value>
      <webElementGuid>c6fb00ad-c03a-40a1-a49f-749da3fb7368</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>5a2ad52b-dc4e-4441-98a4-a83ad314d8f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'Note']</value>
      <webElementGuid>3b6632be-0e10-4bc5-8aa9-062d08914ad2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
