<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>app-root_Processing request .Skip to main c_87e5bb</name>
   <tag></tag>
   <elementGuidId>e94c9415-ef15-4e1f-a0b2-263b77469c59</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//app-root</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>app-root</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>app-root</value>
      <webElementGuid>42131001-fea5-47d1-9725-f096c53f5671</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-version</name>
      <type>Main</type>
      <value>13.1.3</value>
      <webElementGuid>6ddb9400-bd7c-4f07-9eef-1246e12b8b39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Processing request ...Skip to main contentMCDAVersion 9.0.0Menu Manage  Administration My WorkPress Enter to open the Dialog box and then use navigation keys to navigate32Notifications218Press Enter to open the Dialog box and then use navigation keys to navigate218balya I, Pradeep kumarPress Enter to open the Dialog box and then use navigation keys to navigate balya I, Pradeep kumar Name  Case #  LEA #  Court File #  Case Title  Case Keyword  Name  Name (Soundex)  Person SID #  Person ID  Physical File #  Note  All label for searchText No Results FoundInclude Inactive Case TypesInclude Inactive ValuesInclude Temp Cases Case Type Choose Item SelectSelect Operator SelectSelect Value(s)  Hidden TextAddNo Filters AppliedCancelResetSearchSaved SearchesQuick Searchlabel for searchTextAdvance FilterHome3002687Case # 3002687 balya, pradeep kumar, MR.I want to ...Add File LocationAdd New ParticipantAdd Participant InteractionAdd TaskAssign CaseCopy CaseExpunge/UnexpungeSchedule Grand JuryCase Snapshot Add NoteStatus:Pending Review (12/29/2022)Assigned To:DV DDAs  Next Up:Issuing Decision for Custody Case 12/29/2022Order Lab Test 01/03/2023Case OverviewParticipants1Case Charges0Costs0DetailDocuments1Events0Evidence1File Location0Incidents1Notes0Tasks4Witness Management0Case ParticipantsView ParticipantsType or press Enter to show the case participants Edit EvidenceSequence # 1 Evidence Type *SelectBlood Test Blood TestParticipants Defendant-1-balya MR., pradeep kumarPackage DescriptionSelectBox BoxEvidence DescriptionQuantityUnitsSelectKG KGSerial NumberValueAgency RPT #Select64802 64802How RecoveredSeized Dateui-btnSeized Timeui-btnEvid ID #Exhibit #   Is AdmissibleIs Admissible   Is Search WarrantIs Search WarrantDispositionSelectApplied towards financial obligations Applied towards financial obligationsDisposition Dateui-btnEvidence NotesStorage LocationSelectJunction Avenue Evidence Warehouse Junction Avenue Evidence WarehouseSectionShelfFacilitySelectJustice Center Justice CenterSpecial RetentionSelectContraband ContrabandSubmitting AgencySelectAdult and Family Services Adult and Family ServicesSubmitting OfficerSelectAberle, Kenneth Aberle, KennethBar Code Test/Action Summary Add Test/Action  Test/Action  Action Date  Test/Action Id# Test/Action:  Insufficient Blow Action Date:  12/30/2022 Test/Action Id#:  456 Expansion LinkAttachments Add Attachments  Doc Type   Document Title   Uploaded   Status  Doc Type:  Evidence  Document Title:  Document Evidence Title  Uploaded:  01/02/2023 08:01 AM Status:  Pending  Expansion LinkSaveCancel Company Overview  Leadership  Policies  Services  Industries  Partners COPYRIGHT 2020 HTC Global Services.</value>
      <webElementGuid>a9c48800-5f76-40d8-9d6a-6ca8a7bed213</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]</value>
      <webElementGuid>be0c336e-0b1b-400c-9060-0f08cfcfac54</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-root</value>
      <webElementGuid>1278595c-1c71-4e4d-9ba1-a43d8e7f6edc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//app-root[(text() = 'Processing request ...Skip to main contentMCDAVersion 9.0.0Menu Manage  Administration My WorkPress Enter to open the Dialog box and then use navigation keys to navigate32Notifications218Press Enter to open the Dialog box and then use navigation keys to navigate218balya I, Pradeep kumarPress Enter to open the Dialog box and then use navigation keys to navigate balya I, Pradeep kumar Name  Case #  LEA #  Court File #  Case Title  Case Keyword  Name  Name (Soundex)  Person SID #  Person ID  Physical File #  Note  All label for searchText No Results FoundInclude Inactive Case TypesInclude Inactive ValuesInclude Temp Cases Case Type Choose Item SelectSelect Operator SelectSelect Value(s)  Hidden TextAddNo Filters AppliedCancelResetSearchSaved SearchesQuick Searchlabel for searchTextAdvance FilterHome3002687Case # 3002687 balya, pradeep kumar, MR.I want to ...Add File LocationAdd New ParticipantAdd Participant InteractionAdd TaskAssign CaseCopy CaseExpunge/UnexpungeSchedule Grand JuryCase Snapshot Add NoteStatus:Pending Review (12/29/2022)Assigned To:DV DDAs  Next Up:Issuing Decision for Custody Case 12/29/2022Order Lab Test 01/03/2023Case OverviewParticipants1Case Charges0Costs0DetailDocuments1Events0Evidence1File Location0Incidents1Notes0Tasks4Witness Management0Case ParticipantsView ParticipantsType or press Enter to show the case participants Edit EvidenceSequence # 1 Evidence Type *SelectBlood Test Blood TestParticipants Defendant-1-balya MR., pradeep kumarPackage DescriptionSelectBox BoxEvidence DescriptionQuantityUnitsSelectKG KGSerial NumberValueAgency RPT #Select64802 64802How RecoveredSeized Dateui-btnSeized Timeui-btnEvid ID #Exhibit #   Is AdmissibleIs Admissible   Is Search WarrantIs Search WarrantDispositionSelectApplied towards financial obligations Applied towards financial obligationsDisposition Dateui-btnEvidence NotesStorage LocationSelectJunction Avenue Evidence Warehouse Junction Avenue Evidence WarehouseSectionShelfFacilitySelectJustice Center Justice CenterSpecial RetentionSelectContraband ContrabandSubmitting AgencySelectAdult and Family Services Adult and Family ServicesSubmitting OfficerSelectAberle, Kenneth Aberle, KennethBar Code Test/Action Summary Add Test/Action  Test/Action  Action Date  Test/Action Id# Test/Action:  Insufficient Blow Action Date:  12/30/2022 Test/Action Id#:  456 Expansion LinkAttachments Add Attachments  Doc Type   Document Title   Uploaded   Status  Doc Type:  Evidence  Document Title:  Document Evidence Title  Uploaded:  01/02/2023 08:01 AM Status:  Pending  Expansion LinkSaveCancel Company Overview  Leadership  Policies  Services  Industries  Partners COPYRIGHT 2020 HTC Global Services.' or . = 'Processing request ...Skip to main contentMCDAVersion 9.0.0Menu Manage  Administration My WorkPress Enter to open the Dialog box and then use navigation keys to navigate32Notifications218Press Enter to open the Dialog box and then use navigation keys to navigate218balya I, Pradeep kumarPress Enter to open the Dialog box and then use navigation keys to navigate balya I, Pradeep kumar Name  Case #  LEA #  Court File #  Case Title  Case Keyword  Name  Name (Soundex)  Person SID #  Person ID  Physical File #  Note  All label for searchText No Results FoundInclude Inactive Case TypesInclude Inactive ValuesInclude Temp Cases Case Type Choose Item SelectSelect Operator SelectSelect Value(s)  Hidden TextAddNo Filters AppliedCancelResetSearchSaved SearchesQuick Searchlabel for searchTextAdvance FilterHome3002687Case # 3002687 balya, pradeep kumar, MR.I want to ...Add File LocationAdd New ParticipantAdd Participant InteractionAdd TaskAssign CaseCopy CaseExpunge/UnexpungeSchedule Grand JuryCase Snapshot Add NoteStatus:Pending Review (12/29/2022)Assigned To:DV DDAs  Next Up:Issuing Decision for Custody Case 12/29/2022Order Lab Test 01/03/2023Case OverviewParticipants1Case Charges0Costs0DetailDocuments1Events0Evidence1File Location0Incidents1Notes0Tasks4Witness Management0Case ParticipantsView ParticipantsType or press Enter to show the case participants Edit EvidenceSequence # 1 Evidence Type *SelectBlood Test Blood TestParticipants Defendant-1-balya MR., pradeep kumarPackage DescriptionSelectBox BoxEvidence DescriptionQuantityUnitsSelectKG KGSerial NumberValueAgency RPT #Select64802 64802How RecoveredSeized Dateui-btnSeized Timeui-btnEvid ID #Exhibit #   Is AdmissibleIs Admissible   Is Search WarrantIs Search WarrantDispositionSelectApplied towards financial obligations Applied towards financial obligationsDisposition Dateui-btnEvidence NotesStorage LocationSelectJunction Avenue Evidence Warehouse Junction Avenue Evidence WarehouseSectionShelfFacilitySelectJustice Center Justice CenterSpecial RetentionSelectContraband ContrabandSubmitting AgencySelectAdult and Family Services Adult and Family ServicesSubmitting OfficerSelectAberle, Kenneth Aberle, KennethBar Code Test/Action Summary Add Test/Action  Test/Action  Action Date  Test/Action Id# Test/Action:  Insufficient Blow Action Date:  12/30/2022 Test/Action Id#:  456 Expansion LinkAttachments Add Attachments  Doc Type   Document Title   Uploaded   Status  Doc Type:  Evidence  Document Title:  Document Evidence Title  Uploaded:  01/02/2023 08:01 AM Status:  Pending  Expansion LinkSaveCancel Company Overview  Leadership  Policies  Services  Industries  Partners COPYRIGHT 2020 HTC Global Services.')]</value>
      <webElementGuid>78599885-de63-45ba-a5af-af87db05c4c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
