<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Select_ui-dropdown-trigger-icon ui-cli_72ec43</name>
   <tag></tag>
   <elementGuidId>a0004077-1bf2-4e14-bb68-56c6bded1462</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main']/div/div/app-case360/div[2]/div/div/div[2]/div/app-case360-evidence/div/app-case360-evidence-details/div/form/div[3]/app-evidence-test-action-summary/roots-dialog/div/div[2]/roots-scrollpanel/div/div/div/form/div/div[5]/div/roots-dropdown/div/div[4]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.ui-dropdown-trigger-icon.ui-clickable.ng-tns-c50-313.fas.fa-angle-down</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e299313e-427e-4f8b-b41f-150c2389381f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-dropdown-trigger-icon ui-clickable ng-tns-c50-313 fas fa-angle-down</value>
      <webElementGuid>0d4ce593-a11b-4b6d-91fe-e96dbc821b74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;bg-white min-height-600&quot;]/div[@class=&quot;bg-E3E3E3&quot;]/app-case360[@class=&quot;ng-star-inserted&quot;]/div[2]/div[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-9 col-xl-9 mb-3 mb-lg-0 pl-lg-0 pl-xl-0&quot;]/div[@class=&quot;clearfix h-100 bg-white&quot;]/app-case360-evidence[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;container-fluid ng-star-inserted&quot;]/app-case360-evidence-details[1]/div[@class=&quot;addevidence-content&quot;]/form[@class=&quot;ng-valid ng-touched ng-dirty&quot;]/div[@class=&quot;mt-2 ng-star-inserted&quot;]/app-evidence-test-action-summary[1]/roots-dialog[@class=&quot;ng-tns-c52-301 ng-star-inserted&quot;]/div[@class=&quot;ng-trigger ng-trigger-animation ng-tns-c52-301 col-xl-6 col-lg-8 col-md-8 px-0 ui-dialog ui-widget ui-widget-content ui-corner-all ui-shadow ui-dialog-resizable ng-star-inserted&quot;]/div[@class=&quot;ui-dialog-content ui-widget-content ng-tns-c52-301&quot;]/roots-scrollpanel[@class=&quot;ng-tns-c52-301&quot;]/div[@class=&quot;ui-scrollpanel ui-widget ui-widget-content ui-corner-all&quot;]/div[@class=&quot;ui-scrollpanel-wrapper&quot;]/div[@class=&quot;ui-scrollpanel-content&quot;]/form[@class=&quot;ng-touched ng-dirty ng-valid&quot;]/div[@class=&quot;row ng-star-inserted&quot;]/div[@class=&quot;col-md-4 ng-star-inserted&quot;]/div[@class=&quot;form-group&quot;]/roots-dropdown[@class=&quot;roots-form-control ng-tns-c50-313 ng-untouched ng-pristine ng-valid ng-star-inserted&quot;]/div[@class=&quot;ng-tns-c50-313 ui-dropdown ui-widget ui-state-default ui-corner-all ui-helper-clearfix&quot;]/div[@class=&quot;ui-dropdown-trigger ui-state-default ui-corner-right ng-tns-c50-313&quot;]/span[@class=&quot;ui-dropdown-trigger-icon ui-clickable ng-tns-c50-313 fas fa-angle-down&quot;]</value>
      <webElementGuid>f2e79039-9c9b-464d-a1d7-3313061925f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/div/div/app-case360/div[2]/div/div/div[2]/div/app-case360-evidence/div/app-case360-evidence-details/div/form/div[3]/app-evidence-test-action-summary/roots-dialog/div/div[2]/roots-scrollpanel/div/div/div/form/div/div[5]/div/roots-dropdown/div/div[4]/span</value>
      <webElementGuid>dd95b2e2-2c5d-412b-b16f-5d5bc0dba854</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/roots-dropdown/div/div[4]/span</value>
      <webElementGuid>8a08a116-b596-4be0-9605-dc0da1b3cd62</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
